### PR TITLE
Optimise build.sh (GCC) for Jaguar SoC

### PR DESCRIPTION
**Pull request by Strykar**
GCC has its own target for the Jaguar SoCs. We can optimise by using the "-march=btver2 -mtune=btver2" GCC options, with a recent GCC version. See https://github.com/riptidewave93/LEDE-APU2/issues/3

### CODE REVIEW

**Comment by riptidewave93** [comment]
@Strykar is there any reason this is defined when make is ran, instead of in the diffconfig? ex:
CONFIG_TARGET_OPTIMIZATION="-Os -pipe -march=btver2 -mtune=btver2"

**Comment by CRCinAU** [comment]
I annoyed @Strykar enough to start some work on this - but you're right - it probably should be in the diffconfig.

On the same note, I _really_ would like to get this stuff in a position to upstream as a separate target so it becomes one option to get all the differing kmods / patches etc.

**Comment by riptidewave93** [comment]
@CRCinAU If you can get approval to do so, you are more than welcome to use my code and push it upstream. :) There were some plans to tweak the LED/GPIO button to be a bit more universal for the SoC (so future boards can use it as well) but I just need find time to work on it.

As for this patch, once it's revised to use diffconfig I will merge it up.

**Comment by CRCinAU** [comment]
Yeah - if you're about on IRC, jump into Freenode #lede-dev and you'll find both of us there... :)

**Comment by Strykar** [comment]
The diffconfig is probably the right place for it. Closing this PR.

**Pull request closed without merging**
