### PR TITLE
Update Master to match LEDE Upstream - WIP

### PR DESCRIPTION
**Pull request by riptidewave93**
This is a PR to track the progress of the RFCs and code changes made to get this working upstream. All changes in this branch/PR are from the feedback provided via the LEDE-Dev Mailing Lists for the APU2 RFC.

### CODE REVIEW

**Comment by riptidewave93** [comment]
V2 of the RFC was just posted at http://lists.infradead.org/pipermail/lede-dev/2016-October/003536.html which is based on the repo in it's current state.

**Comment by riptidewave93** [comment]
@CRCinAU I2C is a bit tricky on the APU2 due to it's implementation. Long story short, you will need to pick between having I2C, or having the SoC Watchdog driver (sp5100_tco). By default I will leave the Watchdog as the default option, but if you want to enable I2C the process is as follows:
1. Edit ./target/linux/x86/64/config-default and set `CONFIG_SP5100_TCO=y` to `# CONFIG_SP5100_TCO is not set`
2. Add `kmod-i2c-core` and `kmod-i2c-piix4` to ./target/linux/x86/64/profiles/001-PCEngines.mk

This will then disable the hardware watchdog, and enable the i2c bus. Later down the line research can be done into adding watchdog support into the nct5104d driver, as this would give users an option to have a hardware watchdog and I2C at the same time.

With that said, after doing the above steps the I2C interface shows up on my APU2:

```
root@lede:/# dmesg | grep piix
[    9.232275] piix4_smbus 0000:00:14.0: SMBus Host Controller at 0xb00, revision 0
[    9.240324] piix4_smbus 0000:00:14.0: Auxiliary SMBus Host Controller at 0xb20
root@lede:/sys/class/i2c-dev# ls
i2c-0  i2c-1
root@lede:/sys/class/i2c-dev# i2cdetect 0
i2cdetect: WARNING! This program can confuse your I2C bus
Continue? [y/N] y
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: 10 -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --                         
root@lede:/sys/class/i2c-dev# i2cdetect 1
i2cdetect: WARNING! This program can confuse your I2C bus
Continue? [y/N] y
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --                         
root@lede:/sys/class/i2c-dev# 
```

**Comment by CRCinAU** [comment]
Ok, interesting to know. I just finished the code for the Arduino to now drive the LEDs and call it from the i2c bus via:

```
i2cset -y 2 0x08 0x00 0x02 0xFF 0x00 0x00 0x20 i
i2cset -y 2 0x08 0x01 0x01 0xFF 0xFF 0x00 0x20 i
i2cset -y 2 0x08 0x02 0x02 0x00 0xFF 0x00 0x20 i
i2cset -y 2 0x08 0x03 0x01 0x00 0x00 0xFF 0x20 i
i2cset -y 2 0x08 0x04 0x02 0xFF 0x00 0xFF 0x20 i
i2cset -y 2 0x08 0x05 0x01 0xFF 0xFF 0xFF 0x20 i
```

The fields are:
1 - i2C bus address
2 - LED # on the chain (max 0x07) without changing code
3 - Function (0 = RGB Fade, 1 = static, 2 = flash)
4 - Red value (0x00-0xFF)
5 - Green value (0x00-0xFF)
6 - Blue value (0x00-0xFF)
7 - Strip brightness (applies globally)

I'll start packaging this up soon and publish the info on how to build. Its a _very_ easy way to add an 8 LED RGB status indication system to the APU2 (or really any i2c capable device)

**Comment by riptidewave93** [comment]
This is kind of on hold ATM as I am waiting for a few of my previous ML submissions to get replies from upstream maintainers. Until then, there is no real reason to do the next RFC.

**Comment by rotanid** [comment]
@riptidewave93 which submissions in particular? would be nice to reference them here!

**Comment by riptidewave93** [comment]
@rotanid Sure thing, currently the two in waiting are:
beep package: http://lists.infradead.org/pipermail/lede-dev/2016-October/003690.html
sp5100_tco module: http://lists.infradead.org/pipermail/lede-dev/2016-October/003692.html

x86 also needs it's makefile remade in the new format, which I was assuming the maintainer would want to take care of. This was mentioned in the last RFC cover letter: http://lists.infradead.org/pipermail/lede-dev/2016-October/003536.html

**Comment by KyleSanderson** [comment]
@nbd168 any update on this?

**Comment by rotanid** [comment]
@riptidewave93 maybe you have to bump the issues to get attention?
would be nice to have this in LEDE's first release in january...

**Comment by riptidewave93** [comment]
@rotanid sadly I won't have time for another PR until after the holidays, so sadly I would not expect this to be in the first "official" release.

**Comment by riptidewave93** [comment]
PR for beep binary added to OpenWRT feeds at https://github.com/openwrt/packages/pull/3833

**Comment by riptidewave93** [comment]
More patches submitted upstream for review:
sp5100_tco Kernel Patches - http://lists.infradead.org/pipermail/lede-dev/2017-January/005350.html
GPIO Driver - http://lists.infradead.org/pipermail/lede-dev/2017-January/005351.html
LED Driver - http://lists.infradead.org/pipermail/lede-dev/2017-January/005352.html

**Pull request merged**
